# Generated by Django 5.1.3 on 2024-12-26 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empRemail', models.EmailField(max_length=254, unique=True)),
                ('empRmobile', models.CharField(max_length=15)),
                ('empRpassword', models.CharField(max_length=128)),
            ],
        ),
    ]
