# Generated by Django 5.1.3 on 2025-01-07 08:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empregistration', '0002_empuserprofile_full_name_empuserprofile_otp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empuserprofile',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
