# Generated by Django 5.1.3 on 2025-01-08 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basicinformation',
            name='name',
        ),
        migrations.RemoveField(
            model_name='basicinformation',
            name='user',
        ),
        migrations.AddField(
            model_name='basicinformation',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basicinformation',
            name='ctc',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='basicinformation',
            name='experience',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='basicinformation',
            name='github',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basicinformation',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basicinformation',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='basicinformation',
            name='other_links',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basicinformation',
            name='resume_file',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
        migrations.AlterField(
            model_name='basicinformation',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='basicinformation',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
