# Generated by Django 5.1.3 on 2025-01-08 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_remove_basicinformation_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experience',
            old_name='end_date',
            new_name='from_date',
        ),
        migrations.RenameField(
            model_name='experience',
            old_name='start_date',
            new_name='to_date',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='position',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='user',
        ),
        migrations.AddField(
            model_name='experience',
            name='job_role',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='job_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='company',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
