# Generated by Django 5.1.3 on 2025-01-09 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_rename_end_date_experience_from_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='job_role',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
