# Generated by Django 5.1.3 on 2025-01-10 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_experience_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='user',
        ),
        migrations.AlterField(
            model_name='experience',
            name='job_role',
            field=models.TextField(blank=True, null=True),
        ),
    ]
