# Generated by Django 5.1.3 on 2025-01-19 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_remove_experience_user_alter_experience_job_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certification',
            name='user',
        ),
        migrations.RemoveField(
            model_name='education',
            name='user',
        ),
        migrations.RemoveField(
            model_name='language',
            name='user',
        ),
        migrations.RemoveField(
            model_name='project',
            name='user',
        ),
    ]
