# Generated by Django 5.1.3 on 2025-01-22 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_remove_certification_user_remove_education_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certification',
            old_name='date_issued',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='name',
            new_name='project_name',
        ),
        migrations.RemoveField(
            model_name='certification',
            name='issued_by',
        ),
        migrations.RemoveField(
            model_name='project',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='project',
            name='start_date',
        ),
        migrations.AddField(
            model_name='certification',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='certification',
            name='start_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='project_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='timeline',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='language',
            name='proficiency',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Proficient', 'Proficient'), ('Fluent', 'Fluent')], max_length=20),
        ),
    ]
