# Generated by Django 5.1.3 on 2024-12-27 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employerLogin', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='empUserProfile',
        ),
    ]
