# Generated by Django 5.1.3 on 2025-01-23 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobpost', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=80)),
                ('job_description', models.TextField()),
                ('salary_from', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('salary_to', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('work_type', models.CharField(choices=[('In-Office', 'In-Office'), ('Hybrid', 'Hybrid'), ('Remote', 'Remote')], default='In-Office', max_length=20)),
                ('employment_type', models.CharField(choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time'), ('Contract', 'Contract'), ('Internship', 'Internship')], default='Full Time', max_length=20)),
                ('location', models.JSONField(default=list)),
                ('skills', models.JSONField(default=list)),
                ('education_level', models.CharField(blank=True, max_length=50, null=True)),
                ('uploaded_file', models.FileField(blank=True, null=True, upload_to='job_descriptions/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='jobposting',
            name='locations',
        ),
        migrations.RemoveField(
            model_name='jobposting',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='jobposting',
            name='user',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
        migrations.DeleteModel(
            name='JobPosting',
        ),
    ]
