# Generated by Django 5.1.3 on 2024-12-20 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeRegistration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='full_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
